import { TemplateStyle, PosterAspect } from './types';

export const CONTENT_LANGUAGES = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Assamese",
  "Bengali",
  "Bhojpuri",
  "Bulgarian",
  "Burmese",
  "Cebuano",
  "Chichewa",
  "Chinese (Mandarin)",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Finnish",
  "French",
  "German",
  "Greek (Modern)",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Igbo",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Kashmiri",
  "Khmer",
  "Kinyarwanda",
  "Konkani",
  "Korean",
  "Luganda",
  "Maithili",
  "Malagasy",
  "Malayalam",
  "Marathi",
  "Nepali",
  "Nigerian Pidgin",
  "Norwegian",
  "Odia",
  "Persian (Farsi)",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Santali",
  "Shona",
  "Sindhi",
  "Slovak",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog (Filipino)",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Yoruba",
  "Zulu"
];

// Maps our language names to Google Input Tools codes
export const INPUT_METHOD_CODES: Record<string, string> = {
  "Amharic": "am-t-i0-und",
  "Arabic": "ar-t-i0-und",
  "Bengali": "bn-t-i0-und",
  "Chinese (Mandarin)": "zh-t-i0-pinyin",
  "Greek (Modern)": "el-t-i0-und",
  "Gujarati": "gu-t-i0-und",
  "Hindi": "hi-t-i0-und",
  "Kannada": "kn-t-i0-und",
  "Malayalam": "ml-t-i0-und",
  "Marathi": "mr-t-i0-und",
  "Nepali": "ne-t-i0-und",
  "Odia": "or-t-i0-und",
  "Persian (Farsi)": "fa-t-i0-und",
  "Punjabi": "pu-t-i0-und",
  "Russian": "ru-t-i0-und",
  "Sanskrit": "sa-t-i0-und",
  "Sinhala": "si-t-i0-und",
  "Tamil": "ta-t-i0-und",
  "Telugu": "te-t-i0-und",
  "Tigrinya": "ti-t-i0-und",
  "Urdu": "ur-t-i0-und",
  "Serbian": "sr-t-i0-und"
};

export const SUPPORTED_LANGUAGES = [
  { code: 'af', name: 'Afrikaans', bibleVersion: 'web' },
  { code: 'sq', name: 'Albanian', bibleVersion: 'web' },
  { code: 'am', name: 'Amharic', bibleVersion: 'web' },
  { code: 'ar', name: 'Arabic', bibleVersion: 'web' },
  { code: 'as', name: 'Assamese', bibleVersion: 'web' },
  { code: 'bn', name: 'Bengali', bibleVersion: 'web' },
  { code: 'bho', name: 'Bhojpuri', bibleVersion: 'web' },
  { code: 'bg', name: 'Bulgarian', bibleVersion: 'web' },
  { code: 'my', name: 'Burmese', bibleVersion: 'web' },
  { code: 'ceb', name: 'Cebuano', bibleVersion: 'web' },
  { code: 'ny', name: 'Chichewa', bibleVersion: 'web' },
  { code: 'zh', name: 'Chinese (Mandarin)', bibleVersion: 'web' },
  { code: 'hr', name: 'Croatian', bibleVersion: 'web' },
  { code: 'cs', name: 'Czech', bibleVersion: 'web' },
  { code: 'da', name: 'Danish', bibleVersion: 'web' },
  { code: 'nl', name: 'Dutch', bibleVersion: 'web' },
  { code: 'en', name: 'English', bibleVersion: 'web' },
  { code: 'fi', name: 'Finnish', bibleVersion: 'web' },
  { code: 'fr', name: 'Français', bibleVersion: 'ls1910' },
  { code: 'de', name: 'German', bibleVersion: 'web' },
  { code: 'el', name: 'Greek (Modern)', bibleVersion: 'web' },
  { code: 'gu', name: 'Gujarati', bibleVersion: 'web' },
  { code: 'ht', name: 'Haitian Creole', bibleVersion: 'web' },
  { code: 'ha', name: 'Hausa', bibleVersion: 'web' },
  { code: 'hi', name: 'Hindi', bibleVersion: 'web' },
  { code: 'hmn', name: 'Hmong', bibleVersion: 'web' },
  { code: 'hu', name: 'Hungarian', bibleVersion: 'web' },
  { code: 'ig', name: 'Igbo', bibleVersion: 'web' },
  { code: 'id', name: 'Indonesian', bibleVersion: 'web' },
  { code: 'it', name: 'Italian', bibleVersion: 'web' },
  { code: 'ja', name: 'Japanese', bibleVersion: 'web' },
  { code: 'kn', name: 'Kannada', bibleVersion: 'web' },
  { code: 'ks', name: 'Kashmiri', bibleVersion: 'web' },
  { code: 'km', name: 'Khmer', bibleVersion: 'web' },
  { code: 'rw', name: 'Kinyarwanda', bibleVersion: 'web' },
  { code: 'kok', name: 'Konkani', bibleVersion: 'web' },
  { code: 'ko', name: 'Korean', bibleVersion: 'web' },
  { code: 'lg', name: 'Luganda', bibleVersion: 'web' },
  { code: 'mai', name: 'Maithili', bibleVersion: 'web' },
  { code: 'mg', name: 'Malagasy', bibleVersion: 'web' },
  { code: 'ml', name: 'Malayalam', bibleVersion: 'web' },
  { code: 'mr', name: 'Marathi', bibleVersion: 'web' },
  { code: 'ne', name: 'Nepali', bibleVersion: 'web' },
  { code: 'pcm', name: 'Nigerian Pidgin', bibleVersion: 'web' },
  { code: 'no', name: 'Norwegian', bibleVersion: 'web' },
  { code: 'or', name: 'Odia', bibleVersion: 'web' },
  { code: 'fa', name: 'Persian (Farsi)', bibleVersion: 'web' },
  { code: 'pl', name: 'Polish', bibleVersion: 'web' },
  { code: 'pt', name: 'Portuguese', bibleVersion: 'almeida' },
  { code: 'pa', name: 'Punjabi', bibleVersion: 'web' },
  { code: 'ro', name: 'Romanian', bibleVersion: 'cornilescu' },
  { code: 'ru', name: 'Russian', bibleVersion: 'web' },
  { code: 'sat', name: 'Santali', bibleVersion: 'web' },
  { code: 'sn', name: 'Shona', bibleVersion: 'web' },
  { code: 'sd', name: 'Sindhi', bibleVersion: 'web' },
  { code: 'sk', name: 'Slovak', bibleVersion: 'web' },
  { code: 'es', name: 'Español', bibleVersion: 'rvr' },
  { code: 'sw', name: 'Swahili', bibleVersion: 'web' },
  { code: 'sv', name: 'Swedish', bibleVersion: 'web' },
  { code: 'tl', name: 'Tagalog (Filipino)', bibleVersion: 'web' },
  { code: 'ta', name: 'Tamil', bibleVersion: 'web' },
  { code: 'te', name: 'Telugu', bibleVersion: 'web' },
  { code: 'th', name: 'Thai', bibleVersion: 'web' },
  { code: 'tr', name: 'Turkish', bibleVersion: 'web' },
  { code: 'tw', name: 'Twi', bibleVersion: 'web' },
  { code: 'uk', name: 'Ukrainian', bibleVersion: 'web' },
  { code: 'ur', name: 'Urdu', bibleVersion: 'web' },
  { code: 'vi', name: 'Vietnamese', bibleVersion: 'web' },
  { code: 'yo', name: 'Yoruba', bibleVersion: 'web' },
  { code: 'zu', name: 'Zulu', bibleVersion: 'web' }
];

export const UI_TRANSLATIONS: Record<string, any> = {
  en: {
    verse_editor: "Verse Editor",
    event_editor: "Event Editor",
    customize_msg: "Customize your spiritual message.",
    find_verse: "Find Verse",
    search_placeholder: "Type ref (e.g. mark 3:7)...",
    verse_text_placeholder: "Verse text will appear here...",
    event_title: "Event Title",
    event_details: "Details",
    event_details_placeholder: "Date, Time, Venue...",
    typography: "Typography",
    text_color: "Text Color",
    text_effects: "Text Effects",
    footer_label: "Footer Label",
    theme: "Theme",
    generate: "Generate",
    generating: "Generating...",
    ai_bg_desc: "Create a unique, spiritual backdrop with Gemini.",
    typing_mode: "Typing Mode",
    generate_background: "Generate Background"
  },
  es: {
    verse_editor: "Editor de Versículos",
    event_editor: "Editor de Eventos",
    customize_msg: "Personaliza tu mensaje espiritual.",
    find_verse: "Buscar Versículo",
    search_placeholder: "Buscar escritura (ej. Salmos 23)",
    verse_text_placeholder: "El texto aparecerá aquí...",
    event_title: "Título del Evento",
    event_details: "Detalles",
    event_details_placeholder: "Fecha, Hora, Lugar...",
    typography: "Tipografía",
    text_color: "Color de Texto",
    text_effects: "Efectos de Texto",
    footer_label: "Pie de Página",
    theme: "Tema",
    generate: "Generar",
    generating: "Generando...",
    ai_bg_desc: "Crea un fondo espiritual único con Gemini.",
    typing_mode: "Modo de escritura",
    generate_background: "Generar Fondo"
  },
  fr: {
    verse_editor: "Éditeur de Versets",
    event_editor: "Éditeur d'Événements",
    customize_msg: "Personnalisez votre message spirituel.",
    find_verse: "Trouver un Verset",
    search_placeholder: "Rechercher (ex. Psaumes 23)",
    verse_text_placeholder: "Le texte apparaîtra ici...",
    event_title: "Titre de l'événement",
    event_details: "Détails",
    event_details_placeholder: "Date, Heure, Lieu...",
    typography: "Typographie",
    text_color: "Couleur du Texte",
    text_effects: "Effets de Texte",
    footer_label: "Pied de Page",
    theme: "Thème",
    generate: "Générer",
    generating: "Génération...",
    ai_bg_desc: "Créez un fond spirituel unique avec Gemini.",
    typing_mode: "Mode de frappe",
    generate_background: "Générer un arrière-plan"
  },
  // Default fallback for others
  hi: { verse_editor: "वचन संपादक", event_editor: "कार्यक्रम संपादक", find_verse: "वचन खोजें", typography: "टाइपोग्राफी", theme: "विषय", generate_background: "पृष्ठभूमि बनाएं" },
  te: { verse_editor: "వాక్య ఎడిటర్", event_editor: "ఈవెంట్ ఎడిటర్", find_verse: "వాక్యాన్ని వెతకండి", typography: "టైపోగ్రఫీ", theme: "థీమ్", generate_background: "నేపథ్యాన్ని సృష్టించండి" },
  ta: { verse_editor: "வசன எடிட்டர்", event_editor: "நிகழ்வு எடிட்டர்", find_verse: "வசனத்தைத் தேடுங்கள்", typography: "எழுத்துரு", theme: "தீம்", generate_background: "பின்னணியை உருவாக்குங்கள்" },
  ml: { verse_editor: "വാക്യ എഡിറ്റർ", event_editor: "ഇവന്റ് എഡിറ്റർ", find_verse: "വാക്യം കണ്ടെത്തുക", typography: "ടൈപ്പോഗ്രാഫി", theme: "തീം", generate_background: "പശ്ചാത്തലം സൃഷ്ടിക്കുക" },
};

export const AVAILABLE_FONTS = [
  // Serifs
  { name: "Playfair Display (Elegant)", value: "'Playfair Display', serif" },
  { name: "Merriweather (Classic)", value: "'Merriweather', serif" },
  { name: "Lora (Contemporary)", value: "'Lora', serif" },
  { name: "Cinzel (Cinematic)", value: "'Cinzel', serif" },
  { name: "Abril Fatface (Bold)", value: "'Abril Fatface', cursive" },
  { name: "Rye (Western)", value: "'Rye', serif" },
  
  // Sans Serifs
  { name: "Inter (Modern UI)", value: "'Inter', sans-serif" },
  { name: "Roboto (Clean)", value: "'Roboto', sans-serif" },
  { name: "Oswald (Condensed)", value: "'Oswald', sans-serif" },
  { name: "Montserrat (Geometric)", value: "'Montserrat', sans-serif" },
  { name: "Poppins (Rounded)", value: "'Poppins', sans-serif" },
  { name: "Lato (Friendly)", value: "'Lato', sans-serif" },
  { name: "Bebas Neue (Tall)", value: "'Bebas Neue', sans-serif" },
  { name: "Anton (Impact)", value: "'Anton', sans-serif" },
  { name: "Orbitron (Sci-Fi)", value: "'Orbitron', sans-serif" },
  { name: "Audiowide (Techno)", value: "'Audiowide', sans-serif" },

  // Scripts / Handwritten
  { name: "Great Vibes (Formal)", value: "'Great Vibes', cursive" },
  { name: "Dancing Script (Lively)", value: "'Dancing Script', cursive" },
  { name: "Pacifico (Brush)", value: "'Pacifico', cursive" },
  { name: "Lobster (Fun)", value: "'Lobster', cursive" },
  { name: "Caveat (Handwritten)", value: "'Caveat', cursive" },
  { name: "Shadows Into Light (Marker)", value: "'Shadows Into Light', cursive" },
  { name: "Allura (Feminine)", value: "'Allura', cursive" },
  { name: "Sacramento (Monoline)", value: "'Sacramento', cursive" },
  { name: "Satisfy (Brush Script)", value: "'Satisfy', cursive" },
  { name: "Amatic SC (Thin)", value: "'Amatic SC', cursive" },
  { name: "Gloria Hallelujah (Casual)", value: "'Gloria Hallelujah', cursive" },
  { name: "Permanent Marker (Bold)", value: "'Permanent Marker', cursive" },

  // Display / Special
  { name: "Creepster (Horror)", value: "'Creepster', display" },
  { name: "Press Start 2P (Retro)", value: "'Press Start 2P', display" },
  { name: "Special Elite (Typewriter)", value: "'Special Elite', display" },
  { name: "Monoton (Disco)", value: "'Monoton', display" },
  { name: "Bangers (Comic)", value: "'Bangers', display" },
  { name: "Luckiest Guy (Fun)", value: "'Luckiest Guy', display" },

  // Telugu Fonts
  { name: "Ramabhadra (Telugu Bold)", value: "'Ramabhadra', sans-serif" },
  { name: "Tenali Ramakrishna (Telugu)", value: "'Tenali Ramakrishna', sans-serif" },
  { name: "Gidugu (Telugu Simple)", value: "'Gidugu', sans-serif" },
];

export const TEMPLATE_PREVIEWS: Record<TemplateStyle, string> = {
  [TemplateStyle.MINIMAL]: "bg-white border-2 border-slate-200",
  [TemplateStyle.NATURE]: "bg-green-100 border-2 border-green-200",
  [TemplateStyle.ABSTRACT]: "bg-purple-100 border-2 border-purple-200",
  [TemplateStyle.GOLDEN]: "bg-amber-50 border-2 border-amber-200",
  [TemplateStyle.GRADIENT]: "bg-blue-100 border-2 border-blue-200",
};

export const DEFAULT_BACKGROUNDS: Record<TemplateStyle, string> = {
  [TemplateStyle.MINIMAL]: "https://picsum.photos/id/19/800/1000",
  [TemplateStyle.NATURE]: "https://picsum.photos/id/28/800/1000",
  [TemplateStyle.ABSTRACT]: "https://picsum.photos/id/136/800/1000",
  [TemplateStyle.GOLDEN]: "https://picsum.photos/id/250/800/1000",
  [TemplateStyle.GRADIENT]: "https://picsum.photos/id/33/800/1000",
};

export const POSTER_DIMENSIONS: Record<PosterAspect, { width: number; height: number }> = {
  [PosterAspect.PORTRAIT]: { width: 400, height: 500 },
  [PosterAspect.SQUARE]: { width: 450, height: 450 },
  [PosterAspect.LANDSCAPE]: { width: 600, height: 338 }, // 16:9 approx
};